version: '3.7'

services:
  nginx:
    build: ./nginx
    networks:
      - landingpage
    ports:
      # Production port 80
      - "80:80"
      # Dev port 35001
      #- "35001:80"
    volumes:
      - "./nginx/volumes/nginx:/volumes"
      - "./nginx/volumes/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./nginx/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"

  hkweb:
    build: ./hkweb
    networks:
      - landingpage
    volumes:
      - type: "bind"
        source: ./hkweb/hkweb
        target: /rails/hkweb
      - type: "volume"
        source: hkweb_dbs
        target: /rails/hkweb/db/dbs

networks:
  landingpage:

volumes:
  hkweb_dbs:
