version: '3'
services:
  alpine:
    build: .
    networks:
      - landingpage
  nginx:
    build: ./nginx
    networks:
      - landingpage
    ports:
      - "80:80"
    volumes:
      - "./nginx/volumes/nginx:/volumes"
      - "./nginx/volumes/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./nginx/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
  hkweb:
    build: ./rails
    networks:
      - landingpage
    ports:
      - "3000:3000"

networks:
  landingpage:
